name: CI
on:
  push:
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn --frozen-lockfile
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn --frozen-lockfile
      - run: npm run test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-yarn-cache@v1
      - run: yarn --frozen-lockfile
      - run: npm run build:example
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_branch: gh-pages
          build_dir: example
          jekyll: false
          fqdn: "vue-md-loader.wxsm.space"
